export interface CompanionDeviceApp {
  id: string;
  label: string;
  shortLabel: string;
  href: string;
  color: string;
  glyph: string;
  group: 'academie' | 'dowze';
}

/**
 * Catalogue unique des applications embarquées dans les appareils du compagnon.
 * Les routes restent les interfaces réelles de Dowze : aucun écran métier parallèle à maintenir.
 */
export const COMPANION_DEVICE_APPS: CompanionDeviceApp[] = [
  {
    id: 'academie',
    label: 'Dowze Académie',
    shortLabel: 'Académie',
    href: '/dashboard',
    color: '#2563eb',
    glyph: 'A',
    group: 'academie',
  },
  {
    id: 'seance',
    label: 'Ma séance',
    shortLabel: 'Séance',
    href: '/seance',
    color: '#7c3aed',
    glyph: '✦',
    group: 'academie',
  },
  {
    id: 'langues',
    label: 'Cours de langue',
    shortLabel: 'Langues',
    href: '/langues',
    color: '#0891b2',
    glyph: '文',
    group: 'academie',
  },
  {
    id: 'expeditions',
    label: 'Expéditions',
    shortLabel: 'Expéditions',
    href: '/expeditions',
    color: '#059669',
    glyph: '⌁',
    group: 'academie',
  },
  {
    id: 'tests',
    label: 'Tests',
    shortLabel: 'Tests',
    href: '/tests',
    color: '#ea580c',
    glyph: '✓',
    group: 'academie',
  },
  {
    id: 'resultats',
    label: 'Mes résultats',
    shortLabel: 'Résultats',
    href: '/resultats',
    color: '#db2777',
    glyph: '↗',
    group: 'academie',
  },
  {
    id: 'planning',
    label: 'Planning',
    shortLabel: 'Planning',
    href: '/planning',
    color: '#4f46e5',
    glyph: '31',
    group: 'academie',
  },
  {
    id: 'classe',
    label: 'Ma classe',
    shortLabel: 'Classe',
    href: '/communaute',
    color: '#0f766e',
    glyph: '◎',
    group: 'academie',
  },
  {
    id: 'specialisation',
    label: 'Ma spécialisation',
    shortLabel: 'Spécialité',
    href: '/specialisation',
    color: '#9333ea',
    glyph: 'S',
    group: 'academie',
  },
  {
    id: 'passion',
    label: 'Ma passion',
    shortLabel: 'Passion',
    href: '/passion',
    color: '#e11d48',
    glyph: '♥',
    group: 'academie',
  },
  {
    id: 'saut',
    label: 'Saut de Rang',
    shortLabel: 'Saut',
    href: '/saut',
    color: '#ca8a04',
    glyph: '⚡',
    group: 'academie',
  },
  {
    id: 'progression',
    label: 'Ma progression',
    shortLabel: 'Progression',
    href: '/progression',
    color: '#0284c7',
    glyph: 'P',
    group: 'academie',
  },
  {
    id: 'amis',
    label: 'Mes amis',
    shortLabel: 'Amis',
    href: '/amis',
    color: '#14b8a6',
    glyph: '☺',
    group: 'academie',
  },
  {
    id: 'social-messages',
    label: 'Messagerie Académie',
    shortLabel: 'Discussions',
    href: '/messages',
    color: '#22c55e',
    glyph: '↔',
    group: 'academie',
  },
  {
    id: 'carnet',
    label: 'Carnet de bord',
    shortLabel: 'Carnet',
    href: '/carnet',
    color: '#92400e',
    glyph: 'N',
    group: 'academie',
  },
  {
    id: 'validation',
    label: 'Validation',
    shortLabel: 'Validation',
    href: '/validation',
    color: '#16a34a',
    glyph: 'V',
    group: 'academie',
  },
  {
    id: 'store',
    label: 'Applications Dowze',
    shortLabel: 'Apps',
    href: '/store',
    color: '#111827',
    glyph: 'D',
    group: 'dowze',
  },
  {
    id: 'parent',
    label: 'Espace responsable',
    shortLabel: 'Responsable',
    href: '/parent',
    color: '#be123c',
    glyph: 'R',
    group: 'academie',
  },
  {
    id: 'profil',
    label: 'Mon profil',
    shortLabel: 'Profil',
    href: '/profil',
    color: '#475569',
    glyph: '●',
    group: 'dowze',
  },
  {
    id: 'memoire',
    label: 'Mémoire de la Ruche',
    shortLabel: 'Mémoire',
    href: '/memoire',
    color: '#7e22ce',
    glyph: 'M',
    group: 'dowze',
  },
  {
    id: 'autorisations',
    label: 'Autorisations',
    shortLabel: 'Accès',
    href: '/autorisations',
    color: '#334155',
    glyph: '⌾',
    group: 'dowze',
  },
  {
    id: 'runtimes',
    label: 'Moteurs de la Ruche',
    shortLabel: 'Moteurs',
    href: '/runtimes',
    color: '#0369a1',
    glyph: 'R',
    group: 'dowze',
  },
  {
    id: 'attention',
    label: 'Centre d’attention',
    shortLabel: 'Attention',
    href: '/attention',
    color: '#dc2626',
    glyph: '!',
    group: 'dowze',
  },
  {
    id: 'operations',
    label: 'Opérations de la Ruche',
    shortLabel: 'Opérations',
    href: '/operations',
    color: '#4338ca',
    glyph: 'O',
    group: 'dowze',
  },
  {
    id: 'espaces',
    label: 'Espaces installables',
    shortLabel: 'Espaces',
    href: '/espaces',
    color: '#0f766e',
    glyph: 'E',
    group: 'dowze',
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    shortLabel: 'Infra',
    href: '/infrastructure',
    color: '#1e293b',
    glyph: 'I',
    group: 'dowze',
  },
  {
    id: 'copilote',
    label: 'Réglages du Copilote',
    shortLabel: 'Copilote',
    href: '/copilote',
    color: '#6d28d9',
    glyph: 'C',
    group: 'dowze',
  },
];

export function getCompanionDeviceApp(id: string): CompanionDeviceApp | undefined {
  return COMPANION_DEVICE_APPS.find((app) => app.id === id);
}
