// GÉNÉRÉ (scratchpad/gen-furniture.mjs depuis apps/dev assets.ts) — NE PAS ÉDITER À LA MAIN.
// Meubles/props posables du jeu isométrique. Image servie depuis /furniture/<id>.png (PNG transparent).
export interface Furniture { id: string; name: string; cat: string; kind: string; price: number; }
export const FURNITURE: Furniture[] = [
  {"id":"fenetre","name":"Fenêtre","cat":"ouvertures","kind":"wallprop","price":90},
  {"id":"fenetre-ronde","name":"Fenêtre ronde","cat":"ouvertures","kind":"wallprop","price":90},
  {"id":"baie-vitree","name":"Baie vitrée","cat":"ouvertures","kind":"wallprop","price":90},
  {"id":"porte-bois","name":"Porte en bois","cat":"ouvertures","kind":"wallprop","price":90},
  {"id":"porte-vitree","name":"Porte vitrée","cat":"ouvertures","kind":"wallprop","price":90},
  {"id":"lit-simple","name":"Lit simple","cat":"chambre","kind":"prop","price":55},
  {"id":"lit-double","name":"Lit double","cat":"chambre","kind":"prop","price":55},
  {"id":"lit-baldaquin","name":"Lit à baldaquin","cat":"chambre","kind":"prop","price":55},
  {"id":"table-de-nuit","name":"Table de nuit","cat":"chambre","kind":"prop","price":55},
  {"id":"commode","name":"Commode","cat":"chambre","kind":"prop","price":55},
  {"id":"armoire","name":"Armoire","cat":"chambre","kind":"prop","price":55},
  {"id":"coiffeuse","name":"Coiffeuse","cat":"chambre","kind":"prop","price":55},
  {"id":"lampe-chevet","name":"Lampe de chevet","cat":"chambre","kind":"prop","price":55},
  {"id":"etagere-livres","name":"Étagère à livres","cat":"chambre","kind":"wallprop","price":55},
  {"id":"coffre-jouets","name":"Coffre à jouets","cat":"chambre","kind":"prop","price":55},
  {"id":"tapis-rond","name":"Tapis rond","cat":"chambre","kind":"rug","price":55},
  {"id":"canape","name":"Canapé","cat":"salon","kind":"prop","price":55},
  {"id":"fauteuil","name":"Fauteuil","cat":"salon","kind":"prop","price":55},
  {"id":"table-basse","name":"Table basse","cat":"salon","kind":"prop","price":55},
  {"id":"meuble-tv","name":"Meuble TV","cat":"salon","kind":"prop","price":55},
  {"id":"television","name":"Télévision","cat":"salon","kind":"prop","price":55},
  {"id":"bibliotheque","name":"Bibliothèque","cat":"salon","kind":"prop","price":55},
  {"id":"lampadaire","name":"Lampadaire","cat":"salon","kind":"prop","price":55},
  {"id":"cheminee","name":"Cheminée","cat":"salon","kind":"prop","price":55},
  {"id":"plante-salon","name":"Plante d’intérieur","cat":"salon","kind":"prop","price":55},
  {"id":"horloge-murale","name":"Horloge murale","cat":"salon","kind":"wallprop","price":55},
  {"id":"tapis-salon","name":"Tapis rectangulaire","cat":"salon","kind":"rug","price":55},
  {"id":"plan-travail","name":"Plan de travail","cat":"cuisine","kind":"prop","price":55},
  {"id":"evier","name":"Évier","cat":"cuisine","kind":"prop","price":55},
  {"id":"cuisiniere","name":"Cuisinière","cat":"cuisine","kind":"prop","price":55},
  {"id":"frigo","name":"Réfrigérateur","cat":"cuisine","kind":"prop","price":55},
  {"id":"table-cuisine","name":"Table de cuisine","cat":"cuisine","kind":"prop","price":55},
  {"id":"chaise-cuisine","name":"Chaise","cat":"cuisine","kind":"prop","price":55},
  {"id":"placard-haut","name":"Placard mural","cat":"cuisine","kind":"wallprop","price":55},
  {"id":"micro-ondes","name":"Micro-ondes","cat":"cuisine","kind":"prop","price":55},
  {"id":"ilot-central","name":"Îlot central","cat":"cuisine","kind":"prop","price":55},
  {"id":"etagere-epices","name":"Étagère à épices","cat":"cuisine","kind":"wallprop","price":55},
  {"id":"bureau","name":"Bureau","cat":"bureau","kind":"prop","price":55},
  {"id":"chaise-bureau","name":"Chaise de bureau","cat":"bureau","kind":"prop","price":55},
  {"id":"ordinateur","name":"Ordinateur","cat":"bureau","kind":"prop","price":55},
  {"id":"lampe-bureau","name":"Lampe de bureau","cat":"bureau","kind":"prop","price":55},
  {"id":"tableau-blanc","name":"Tableau blanc","cat":"bureau","kind":"prop","price":55},
  {"id":"globe","name":"Globe terrestre","cat":"bureau","kind":"prop","price":55},
  {"id":"pile-livres","name":"Pile de livres","cat":"bureau","kind":"prop","price":55},
  {"id":"plante-bureau","name":"Petite plante","cat":"bureau","kind":"prop","price":55},
  {"id":"corbeille","name":"Corbeille","cat":"bureau","kind":"prop","price":55},
  {"id":"bibliotheque-bureau","name":"Étagère bureau","cat":"bureau","kind":"prop","price":55},
  {"id":"coussin","name":"Coussin","cat":"deco","kind":"prop","price":30},
  {"id":"guirlande","name":"Guirlande lumineuse","cat":"deco","kind":"wallprop","price":30},
  {"id":"bougie","name":"Bougie","cat":"deco","kind":"prop","price":30},
  {"id":"vase-fleurs","name":"Vase de fleurs","cat":"deco","kind":"prop","price":30},
  {"id":"miroir","name":"Miroir","cat":"deco","kind":"prop","price":30},
  {"id":"cadre-photo","name":"Cadre photo","cat":"deco","kind":"wallprop","price":30},
  {"id":"tableau-art","name":"Tableau","cat":"deco","kind":"wallprop","price":30},
  {"id":"plante-suspendue","name":"Plante suspendue","cat":"deco","kind":"wallprop","price":30},
  {"id":"pouf","name":"Pouf","cat":"deco","kind":"prop","price":30},
  {"id":"panier-osier","name":"Panier en osier","cat":"deco","kind":"prop","price":30},
  {"id":"aquarium","name":"Aquarium","cat":"deco","kind":"prop","price":30},
  {"id":"horloge-coucou","name":"Horloge coucou","cat":"deco","kind":"wallprop","price":30},
  {"id":"banc-jardin","name":"Banc de jardin","cat":"jardin","kind":"prop","price":55},
  {"id":"table-pique-nique","name":"Table de pique-nique","cat":"jardin","kind":"prop","price":55},
  {"id":"barbecue","name":"Barbecue","cat":"jardin","kind":"prop","price":55},
  {"id":"balancoire","name":"Balançoire","cat":"jardin","kind":"prop","price":55},
  {"id":"cabane-oiseaux","name":"Nichoir","cat":"jardin","kind":"prop","price":55},
  {"id":"arrosoir","name":"Arrosoir","cat":"jardin","kind":"prop","price":55},
  {"id":"brouette","name":"Brouette","cat":"jardin","kind":"prop","price":55},
  {"id":"pot-fleurs-ext","name":"Jardinière","cat":"jardin","kind":"prop","price":55},
  {"id":"lampadaire-jardin","name":"Lanterne de jardin","cat":"jardin","kind":"prop","price":55},
  {"id":"bac-a-sable","name":"Bac à sable","cat":"jardin","kind":"prop","price":55},
  {"id":"puits","name":"Puits","cat":"jardin","kind":"prop","price":55},
  {"id":"cabanon","name":"Cabanon de jardin","cat":"jardin","kind":"prop","price":55},
  {"id":"cloture-bois","name":"Clôture bois","cat":"jardin","kind":"prop","price":55},
  {"id":"haie","name":"Haie","cat":"jardin","kind":"prop","price":55},
  {"id":"parasol","name":"Parasol","cat":"plage","kind":"prop","price":55},
  {"id":"transat","name":"Transat","cat":"plage","kind":"prop","price":55},
  {"id":"chateau-sable","name":"Château de sable","cat":"plage","kind":"prop","price":55},
  {"id":"ballon-plage","name":"Ballon de plage","cat":"plage","kind":"prop","price":55},
  {"id":"seau-pelle","name":"Seau et pelle","cat":"plage","kind":"prop","price":55},
  {"id":"serviette-plage","name":"Serviette de plage","cat":"plage","kind":"rug","price":55},
  {"id":"bouee","name":"Bouée","cat":"plage","kind":"prop","price":55},
  {"id":"palmier","name":"Palmier","cat":"plage","kind":"prop","price":55},
  {"id":"coquillage","name":"Coquillage","cat":"plage","kind":"prop","price":55},
  {"id":"glaciere","name":"Glacière","cat":"plage","kind":"prop","price":55},
  {"id":"planche-surf","name":"Planche de surf","cat":"plage","kind":"prop","price":55},
  {"id":"cabine-plage","name":"Cabine de plage","cat":"plage","kind":"prop","price":55},
  {"id":"arbre-rond","name":"Arbre rond","cat":"nature","kind":"prop","price":30},
  {"id":"sapin","name":"Sapin","cat":"nature","kind":"prop","price":30},
  {"id":"buisson","name":"Buisson","cat":"nature","kind":"prop","price":30},
  {"id":"fleur-tulipe","name":"Tulipes","cat":"nature","kind":"prop","price":30},
  {"id":"tournesol","name":"Tournesol","cat":"nature","kind":"prop","price":30},
  {"id":"cactus","name":"Cactus","cat":"nature","kind":"prop","price":30},
  {"id":"champignon","name":"Champignon","cat":"nature","kind":"prop","price":30},
  {"id":"rocher","name":"Rocher","cat":"nature","kind":"prop","price":30},
  {"id":"souche","name":"Souche","cat":"nature","kind":"prop","price":30},
  {"id":"nenuphar","name":"Nénuphar","cat":"nature","kind":"rug","price":30},
  {"id":"bambou","name":"Bambou","cat":"nature","kind":"prop","price":30},
  {"id":"bosquet-fleurs","name":"Massif de fleurs","cat":"nature","kind":"prop","price":30},
  {"id":"ballon","name":"Ballon","cat":"objets","kind":"prop","price":30},
  {"id":"livre-magique","name":"Livre","cat":"objets","kind":"prop","price":30},
  {"id":"cle","name":"Clé","cat":"objets","kind":"prop","price":30},
  {"id":"cadeau","name":"Cadeau","cat":"objets","kind":"prop","price":30},
  {"id":"trophee","name":"Trophée","cat":"objets","kind":"prop","price":30},
  {"id":"medaille","name":"Médaille","cat":"objets","kind":"prop","price":30},
  {"id":"potion","name":"Potion","cat":"objets","kind":"prop","price":30},
  {"id":"piece-or","name":"Pièce d’or","cat":"objets","kind":"prop","price":30},
  {"id":"cristal","name":"Cristal","cat":"objets","kind":"prop","price":30},
  {"id":"coeur","name":"Cœur","cat":"objets","kind":"prop","price":30},
  {"id":"etoile","name":"Étoile","cat":"objets","kind":"prop","price":30},
  {"id":"cloche","name":"Clochette","cat":"objets","kind":"prop","price":30},
  {"id":"pomme","name":"Pomme","cat":"nourriture","kind":"prop","price":30},
  {"id":"gateau","name":"Gâteau","cat":"nourriture","kind":"prop","price":30},
  {"id":"cupcake","name":"Cupcake","cat":"nourriture","kind":"prop","price":30},
  {"id":"part-pizza","name":"Part de pizza","cat":"nourriture","kind":"prop","price":30},
  {"id":"glace-cornet","name":"Glace","cat":"nourriture","kind":"prop","price":30},
  {"id":"biscuit","name":"Biscuit","cat":"nourriture","kind":"prop","price":30},
  {"id":"bol-nouilles","name":"Bol de nouilles","cat":"nourriture","kind":"prop","price":30},
  {"id":"sushi","name":"Sushi","cat":"nourriture","kind":"prop","price":30},
  {"id":"croissant","name":"Croissant","cat":"nourriture","kind":"prop","price":30},
  {"id":"chocolat-chaud","name":"Chocolat chaud","cat":"nourriture","kind":"prop","price":30},
  {"id":"fraise","name":"Fraise","cat":"nourriture","kind":"prop","price":30},
  {"id":"carotte","name":"Carotte","cat":"nourriture","kind":"prop","price":30},
  {"id":"bureau-travail","name":"Bureau","cat":"travail","kind":"prop","price":55},
  {"id":"double-ecran","name":"Double écran","cat":"travail","kind":"prop","price":55},
  {"id":"ordinateur-portable","name":"Ordinateur portable","cat":"travail","kind":"prop","price":55},
  {"id":"imprimante","name":"Imprimante","cat":"travail","kind":"prop","price":55},
  {"id":"photocopieuse","name":"Photocopieuse","cat":"travail","kind":"prop","price":55},
  {"id":"armoire-dossiers","name":"Armoire à dossiers","cat":"travail","kind":"prop","price":55},
  {"id":"casier-employe","name":"Casier","cat":"travail","kind":"prop","price":55},
  {"id":"cloison-bureau","name":"Cloison de bureau","cat":"travail","kind":"prop","price":55},
  {"id":"fontaine-eau","name":"Fontaine à eau","cat":"travail","kind":"prop","price":55},
  {"id":"corbeille-papier","name":"Corbeille à papier","cat":"travail","kind":"prop","price":55},
  {"id":"pile-dossiers","name":"Pile de dossiers","cat":"travail","kind":"prop","price":55},
  {"id":"telephone-bureau","name":"Téléphone de bureau","cat":"travail","kind":"prop","price":55},
  {"id":"serveur-informatique","name":"Serveur informatique","cat":"travail","kind":"prop","price":55},
  {"id":"projecteur","name":"Vidéoprojecteur","cat":"travail","kind":"prop","price":55},
  {"id":"tableau-liege","name":"Tableau en liège","cat":"travail","kind":"wallprop","price":55},
  {"id":"horloge-bureau","name":"Horloge de bureau","cat":"travail","kind":"wallprop","price":55},
  {"id":"extincteur","name":"Extincteur","cat":"travail","kind":"wallprop","price":55},
  {"id":"panneau-sortie","name":"Panneau sortie","cat":"travail","kind":"wallprop","price":55},
  {"id":"table-cantine","name":"Table de cantine","cat":"cantine","kind":"prop","price":55},
  {"id":"distributeur-boissons","name":"Distributeur de boissons","cat":"cantine","kind":"prop","price":55},
  {"id":"distributeur-snacks","name":"Distributeur de snacks","cat":"cantine","kind":"prop","price":55},
  {"id":"machine-cafe","name":"Machine à café","cat":"cantine","kind":"prop","price":55},
  {"id":"refrigerateur-cantine","name":"Réfrigérateur","cat":"cantine","kind":"prop","price":55},
  {"id":"comptoir-self","name":"Comptoir self-service","cat":"cantine","kind":"prop","price":55},
  {"id":"plateau-repas","name":"Plateau-repas","cat":"cantine","kind":"prop","price":55},
  {"id":"poubelle-tri","name":"Poubelles de tri","cat":"cantine","kind":"prop","price":55},
  {"id":"menu-mural","name":"Menu mural","cat":"cantine","kind":"wallprop","price":55},
  {"id":"wc-cuvette","name":"Cuvette WC","cat":"sanitaires","kind":"prop","price":55},
  {"id":"cabine-wc","name":"Cabine WC","cat":"sanitaires","kind":"prop","price":55},
  {"id":"lavabo","name":"Lavabo","cat":"sanitaires","kind":"prop","price":55},
  {"id":"urinoir","name":"Urinoir","cat":"sanitaires","kind":"wallprop","price":55},
  {"id":"miroir-toilettes","name":"Miroir","cat":"sanitaires","kind":"wallprop","price":55},
  {"id":"seche-mains","name":"Sèche-mains","cat":"sanitaires","kind":"wallprop","price":55},
  {"id":"distributeur-savon","name":"Distributeur de savon","cat":"sanitaires","kind":"wallprop","price":55},
  {"id":"distributeur-papier","name":"Distributeur de papier","cat":"sanitaires","kind":"wallprop","price":55},
  {"id":"poubelle-toilettes","name":"Poubelle","cat":"sanitaires","kind":"prop","price":55},
  {"id":"canape-repos","name":"Canapé lounge","cat":"repos","kind":"prop","price":55},
  {"id":"pouf-repos","name":"Pouf","cat":"repos","kind":"prop","price":55},
  {"id":"baby-foot","name":"Baby-foot","cat":"repos","kind":"prop","price":55},
  {"id":"billard","name":"Billard","cat":"repos","kind":"prop","price":55},
  {"id":"borne-arcade","name":"Borne d’arcade","cat":"repos","kind":"prop","price":55},
  {"id":"table-ping-pong","name":"Table de ping-pong","cat":"repos","kind":"prop","price":55},
  {"id":"machine-cafe-repos","name":"Coin café","cat":"repos","kind":"prop","price":55},
  {"id":"plante-repos","name":"Grande plante","cat":"repos","kind":"prop","price":55},
  {"id":"voiture","name":"Voiture","cat":"garage","kind":"prop","price":55},
  {"id":"camionnette","name":"Camionnette","cat":"garage","kind":"prop","price":55},
  {"id":"velo-parking","name":"Range-vélos","cat":"garage","kind":"prop","price":55},
  {"id":"borne-recharge","name":"Borne de recharge","cat":"garage","kind":"prop","price":55},
  {"id":"etabli-garage","name":"Établi","cat":"garage","kind":"prop","price":55},
  {"id":"caisse-outils","name":"Caisse à outils","cat":"garage","kind":"prop","price":55},
  {"id":"bidon-huile","name":"Bidon d’huile","cat":"garage","kind":"prop","price":55},
  {"id":"pile-pneus","name":"Pile de pneus","cat":"garage","kind":"prop","price":55},
  {"id":"plot-signalisation","name":"Cône de signalisation","cat":"garage","kind":"prop","price":55},
  {"id":"place-parking","name":"Place de parking","cat":"garage","kind":"rug","price":55},
  {"id":"panneau-parking","name":"Panneau parking","cat":"garage","kind":"wallprop","price":55},
];
export const FURNITURE_PRICES: Record<string, number> = {"fenetre":90,"fenetre-ronde":90,"baie-vitree":90,"porte-bois":90,"porte-vitree":90,"lit-simple":55,"lit-double":55,"lit-baldaquin":55,"table-de-nuit":55,"commode":55,"armoire":55,"coiffeuse":55,"lampe-chevet":55,"etagere-livres":55,"coffre-jouets":55,"tapis-rond":55,"canape":55,"fauteuil":55,"table-basse":55,"meuble-tv":55,"television":55,"bibliotheque":55,"lampadaire":55,"cheminee":55,"plante-salon":55,"horloge-murale":55,"tapis-salon":55,"plan-travail":55,"evier":55,"cuisiniere":55,"frigo":55,"table-cuisine":55,"chaise-cuisine":55,"placard-haut":55,"micro-ondes":55,"ilot-central":55,"etagere-epices":55,"bureau":55,"chaise-bureau":55,"ordinateur":55,"lampe-bureau":55,"tableau-blanc":55,"globe":55,"pile-livres":55,"plante-bureau":55,"corbeille":55,"bibliotheque-bureau":55,"coussin":30,"guirlande":30,"bougie":30,"vase-fleurs":30,"miroir":30,"cadre-photo":30,"tableau-art":30,"plante-suspendue":30,"pouf":30,"panier-osier":30,"aquarium":30,"horloge-coucou":30,"banc-jardin":55,"table-pique-nique":55,"barbecue":55,"balancoire":55,"cabane-oiseaux":55,"arrosoir":55,"brouette":55,"pot-fleurs-ext":55,"lampadaire-jardin":55,"bac-a-sable":55,"puits":55,"cabanon":55,"cloture-bois":55,"haie":55,"parasol":55,"transat":55,"chateau-sable":55,"ballon-plage":55,"seau-pelle":55,"serviette-plage":55,"bouee":55,"palmier":55,"coquillage":55,"glaciere":55,"planche-surf":55,"cabine-plage":55,"arbre-rond":30,"sapin":30,"buisson":30,"fleur-tulipe":30,"tournesol":30,"cactus":30,"champignon":30,"rocher":30,"souche":30,"nenuphar":30,"bambou":30,"bosquet-fleurs":30,"ballon":30,"livre-magique":30,"cle":30,"cadeau":30,"trophee":30,"medaille":30,"potion":30,"piece-or":30,"cristal":30,"coeur":30,"etoile":30,"cloche":30,"pomme":30,"gateau":30,"cupcake":30,"part-pizza":30,"glace-cornet":30,"biscuit":30,"bol-nouilles":30,"sushi":30,"croissant":30,"chocolat-chaud":30,"fraise":30,"carotte":30,"bureau-travail":55,"double-ecran":55,"ordinateur-portable":55,"imprimante":55,"photocopieuse":55,"armoire-dossiers":55,"casier-employe":55,"cloison-bureau":55,"fontaine-eau":55,"corbeille-papier":55,"pile-dossiers":55,"telephone-bureau":55,"serveur-informatique":55,"projecteur":55,"tableau-liege":55,"horloge-bureau":55,"extincteur":55,"panneau-sortie":55,"table-cantine":55,"distributeur-boissons":55,"distributeur-snacks":55,"machine-cafe":55,"refrigerateur-cantine":55,"comptoir-self":55,"plateau-repas":55,"poubelle-tri":55,"menu-mural":55,"wc-cuvette":55,"cabine-wc":55,"lavabo":55,"urinoir":55,"miroir-toilettes":55,"seche-mains":55,"distributeur-savon":55,"distributeur-papier":55,"poubelle-toilettes":55,"canape-repos":55,"pouf-repos":55,"baby-foot":55,"billard":55,"borne-arcade":55,"table-ping-pong":55,"machine-cafe-repos":55,"plante-repos":55,"voiture":55,"camionnette":55,"velo-parking":55,"borne-recharge":55,"etabli-garage":55,"caisse-outils":55,"bidon-huile":55,"pile-pneus":55,"plot-signalisation":55,"place-parking":55,"panneau-parking":55};
export const FURNITURE_CATS: { id: string; label: string; zone: string }[] = [{"id":"ouvertures","label":"Portes & fenêtres","zone":"Intérieur"},{"id":"chambre","label":"Chambre","zone":"Intérieur"},{"id":"salon","label":"Salon","zone":"Intérieur"},{"id":"cuisine","label":"Cuisine","zone":"Intérieur"},{"id":"bureau","label":"Bureau","zone":"Intérieur"},{"id":"deco","label":"Déco & accessoires","zone":"Intérieur"},{"id":"jardin","label":"Jardin","zone":"Extérieur"},{"id":"plage","label":"Plage","zone":"Extérieur"},{"id":"nature","label":"Nature & plantes","zone":"Extérieur"},{"id":"objets","label":"Objets & items","zone":"Mixte"},{"id":"nourriture","label":"Nourriture","zone":"Mixte"},{"id":"travail","label":"Espace de travail","zone":"Intérieur"},{"id":"cantine","label":"Cantine (entreprise)","zone":"Intérieur"},{"id":"sanitaires","label":"Toilettes (entreprise)","zone":"Intérieur"},{"id":"repos","label":"Espace de repos","zone":"Intérieur"},{"id":"garage","label":"Garage & parking","zone":"Mixte"}];
export const furnUrl = (id: string) => `/furniture/${id}.png`;
