// Généré par scratchpad/gen2.mjs — NE PAS éditer à la main.
export const FLOOR_MATS: { id: string; name: string }[] = [
  { id: 'sol-bois-clair', name: "Parquet clair" },
  { id: 'sol-bois-fonce', name: "Parquet foncé" },
  { id: 'sol-chevron', name: "Parquet chevron" },
  { id: 'sol-carrelage-damier', name: "Carrelage damier" },
  { id: 'sol-carrelage-blanc', name: "Carrelage blanc" },
  { id: 'sol-moquette', name: "Moquette" },
  { id: 'sol-beton', name: "Béton ciré" },
  { id: 'sol-marbre', name: "Marbre" },
  { id: 'sol-herbe', name: "Herbe" },
  { id: 'sol-sable', name: "Sable" },
  { id: 'sol-terre', name: "Terre battue" },
  { id: 'sol-pierre', name: "Pavés" },
  { id: 'sol-eau', name: "Eau" },
  { id: 'sol-neige', name: "Neige" },
  { id: 'sol-parquet-chene', name: "Parquet chêne" },
  { id: 'sol-parquet-noyer', name: "Parquet noyer" },
  { id: 'sol-parquet-acajou', name: "Parquet acajou" },
  { id: 'sol-parquet-hetre', name: "Parquet hêtre" },
  { id: 'sol-parquet-teck', name: "Parquet teck" },
  { id: 'sol-parquet-ebene', name: "Parquet ébène" },
  { id: 'sol-parquet-gris', name: "Parquet gris" },
  { id: 'sol-parquet-blanchi', name: "Parquet blanchi" },
  { id: 'sol-parquet-miel', name: "Parquet miel" },
  { id: 'sol-parquet-rouge', name: "Parquet rouge" },
  { id: 'sol-parquet-cendre', name: "Parquet cendré" },
  { id: 'sol-parquet-caramel', name: "Parquet caramel" },
  { id: 'sol-chevron-chene', name: "Chevron chêne" },
  { id: 'sol-chevron-noyer', name: "Chevron noyer" },
  { id: 'sol-chevron-acajou', name: "Chevron acajou" },
  { id: 'sol-chevron-hetre', name: "Chevron hêtre" },
  { id: 'sol-chevron-teck', name: "Chevron teck" },
  { id: 'sol-chevron-ebene', name: "Chevron ébène" },
  { id: 'sol-chevron-gris', name: "Chevron gris" },
  { id: 'sol-chevron-blanchi', name: "Chevron blanchi" },
  { id: 'sol-damier-blanc-noir', name: "Damier blanc & noir" },
  { id: 'sol-damier-blanc-gris', name: "Damier blanc & gris" },
  { id: 'sol-damier-creme-terracotta', name: "Damier crème & terracotta" },
  { id: 'sol-damier-blanc-bleu', name: "Damier blanc & bleu" },
  { id: 'sol-damier-blanc-vert', name: "Damier blanc & vert" },
  { id: 'sol-damier-blanc-rose', name: "Damier blanc & rose" },
  { id: 'sol-damier-ivoire-ardoise', name: "Damier ivoire & ardoise" },
  { id: 'sol-damier-creme-caramel', name: "Damier crème & caramel" },
  { id: 'sol-damier-blanc-menthe', name: "Damier blanc & menthe" },
  { id: 'sol-damier-blanc-jaune', name: "Damier blanc & jaune" },
  { id: 'sol-damier-blanc-corail', name: "Damier blanc & corail" },
  { id: 'sol-damier-gris-anthracite', name: "Damier gris & anthracite" },
  { id: 'sol-carrelage-creme', name: "Carrelage crème" },
  { id: 'sol-carrelage-gris', name: "Carrelage gris" },
  { id: 'sol-carrelage-ardoise', name: "Carrelage ardoise" },
  { id: 'sol-carrelage-sauge', name: "Carrelage sauge" },
  { id: 'sol-carrelage-menthe', name: "Carrelage menthe" },
  { id: 'sol-carrelage-bleu', name: "Carrelage bleu" },
  { id: 'sol-carrelage-ciel', name: "Carrelage ciel" },
  { id: 'sol-carrelage-rose', name: "Carrelage rose" },
  { id: 'sol-carrelage-terracotta', name: "Carrelage terracotta" },
  { id: 'sol-carrelage-moutarde', name: "Carrelage moutarde" },
  { id: 'sol-carrelage-lavande', name: "Carrelage lavande" },
  { id: 'sol-marbre-blanc', name: "Marbre blanc" },
  { id: 'sol-marbre-gris', name: "Marbre gris" },
  { id: 'sol-marbre-noir', name: "Marbre noir" },
  { id: 'sol-marbre-rose', name: "Marbre rose" },
  { id: 'sol-marbre-vert', name: "Marbre vert" },
  { id: 'sol-marbre-bleu', name: "Marbre bleu" },
  { id: 'sol-beton-gris', name: "Béton gris" },
  { id: 'sol-beton-grisclair', name: "Béton gris clair" },
  { id: 'sol-beton-galet', name: "Béton galet" },
  { id: 'sol-beton-sable', name: "Béton sable" },
  { id: 'sol-beton-anthracite', name: "Béton anthracite" },
  { id: 'sol-paves-galet', name: "Pavés galet" },
  { id: 'sol-paves-gris', name: "Pavés gris" },
  { id: 'sol-paves-sable', name: "Pavés sable" },
  { id: 'sol-paves-ardoise', name: "Pavés ardoise" },
  { id: 'sol-paves-brun', name: "Pavés brun" },
  { id: 'sol-terrazzo-creme', name: "Terrazzo crème" },
  { id: 'sol-terrazzo-blanc', name: "Terrazzo blanc" },
  { id: 'sol-terrazzo-rose', name: "Terrazzo rose" },
  { id: 'sol-terrazzo-menthe', name: "Terrazzo menthe" },
  { id: 'sol-terrazzo-gris', name: "Terrazzo gris" },
  { id: 'sol-terrazzo-sable', name: "Terrazzo sable" },
  { id: 'sol-moquette-vieuxrose', name: "Moquette vieux rose" },
  { id: 'sol-moquette-gris', name: "Moquette gris" },
  { id: 'sol-moquette-sauge', name: "Moquette sauge" },
  { id: 'sol-moquette-bleu', name: "Moquette bleu" },
  { id: 'sol-moquette-moutarde', name: "Moquette moutarde" },
  { id: 'sol-moquette-lavande', name: "Moquette lavande" },
  { id: 'sol-moquette-menthe', name: "Moquette menthe" },
  { id: 'sol-moquette-terracotta', name: "Moquette terracotta" },
  { id: 'sol-gravier', name: "Gravier" },
  { id: 'sol-galets', name: "Galets" },
  { id: 'sol-mousse', name: "Mousse" },
  { id: 'sol-feuilles', name: "Feuilles" },
  { id: 'sol-glace', name: "Glace" },
  { id: 'sol-lave', name: "Lave" },
  { id: 'sol-boue', name: "Boue" },
  { id: 'sol-ardoise', name: "Ardoise" },
  { id: 'sol-brique-sol', name: "Briques au sol" },
  { id: 'sol-neige-glace', name: "Névé" },
  { id: 'sol-mosaique-mer', name: "Mosaïque mer" },
  { id: 'sol-mosaique-terre', name: "Mosaïque terre" },
  { id: 'sol-mosaique-jardin', name: "Mosaïque jardin" },
  { id: 'sol-mosaique-rose', name: "Mosaïque rose" },
  { id: 'sol-metal', name: "Métal" },
  { id: 'sol-dalle-gris', name: "Grande dalle gris" },
  { id: 'sol-dalle-ardoise', name: "Grande dalle ardoise" },
  { id: 'sol-dalle-creme', name: "Grande dalle crème" },
  { id: 'sol-rayures-creme-sauge', name: "Rayures crème & sauge" },
  { id: 'sol-rayures-blanc-bleu', name: "Rayures blanc & bleu" },
  { id: 'sol-rayures-creme-terracotta', name: "Rayures crème & terracotta" },
  { id: 'sol-rayures-blanc-gris', name: "Rayures blanc & gris" },
  { id: 'sol-pois-creme-terracotta', name: "Pois crème" },
  { id: 'sol-pois-blanc-ardoise', name: "Pois blanc" },
  { id: 'sol-pois-sauge-creme', name: "Pois sauge" },
];
export const WALL_MATS: { id: string; name: string }[] = [
  { id: 'mur-pastel', name: "Peinture pastel" },
  { id: 'mur-papier-fleuri', name: "Papier fleuri" },
  { id: 'mur-brique', name: "Brique" },
  { id: 'mur-bois', name: "Lambris bois" },
  { id: 'mur-carrelage', name: "Carrelage cuisine" },
  { id: 'mur-rayures', name: "Rayures" },
  { id: 'mur-crepi', name: "Crépi extérieur" },
  { id: 'mur-uni-blanc', name: "Uni blanc" },
  { id: 'mur-uni-creme', name: "Uni crème" },
  { id: 'mur-uni-ivoire', name: "Uni ivoire" },
  { id: 'mur-uni-beige', name: "Uni beige" },
  { id: 'mur-uni-gris', name: "Uni gris" },
  { id: 'mur-uni-grisclair', name: "Uni gris clair" },
  { id: 'mur-uni-ardoise', name: "Uni ardoise" },
  { id: 'mur-uni-sauge', name: "Uni sauge" },
  { id: 'mur-uni-menthe', name: "Uni menthe" },
  { id: 'mur-uni-vert', name: "Uni vert" },
  { id: 'mur-uni-olive', name: "Uni olive" },
  { id: 'mur-uni-bleu', name: "Uni bleu" },
  { id: 'mur-uni-ciel', name: "Uni ciel" },
  { id: 'mur-uni-canard', name: "Uni canard" },
  { id: 'mur-uni-turquoise', name: "Uni turquoise" },
  { id: 'mur-uni-rose', name: "Uni rose" },
  { id: 'mur-uni-poudre', name: "Uni poudré" },
  { id: 'mur-uni-corail', name: "Uni corail" },
  { id: 'mur-uni-moutarde', name: "Uni moutarde" },
  { id: 'mur-uni-jaune', name: "Uni jaune" },
  { id: 'mur-uni-lilas', name: "Uni lilas" },
  { id: 'mur-uni-lavande', name: "Uni lavande" },
  { id: 'mur-uni-violet', name: "Uni violet" },
  { id: 'mur-uni-taupe', name: "Uni taupe" },
  { id: 'mur-rayures-blanc-bleu', name: "Rayures blanc & bleu" },
  { id: 'mur-rayures-blanc-sauge', name: "Rayures blanc & sauge" },
  { id: 'mur-rayures-creme-terracotta', name: "Rayures crème & terracotta" },
  { id: 'mur-rayures-blanc-rose', name: "Rayures blanc & rose" },
  { id: 'mur-rayures-blanc-gris', name: "Rayures blanc & gris" },
  { id: 'mur-rayures-creme-menthe', name: "Rayures crème & menthe" },
  { id: 'mur-rayures-blanc-moutarde', name: "Rayures blanc & moutarde" },
  { id: 'mur-rayures-blanc-lavande', name: "Rayures blanc & lavande" },
  { id: 'mur-rayures-ivoire-canard', name: "Rayures ivoire & canard" },
  { id: 'mur-rayures-blanc-corail', name: "Rayures blanc & corail" },
  { id: 'mur-rayures-creme-vert', name: "Rayures crème & vert" },
  { id: 'mur-rayures-blanc-ardoise', name: "Rayures blanc & ardoise" },
  { id: 'mur-rayures-poudre-blanc', name: "Rayures poudré & blanc" },
  { id: 'mur-rayures-ciel-blanc', name: "Rayures ciel & blanc" },
  { id: 'mur-rayures-creme-bordeaux', name: "Rayures crème & bordeaux" },
  { id: 'mur-rayures-blanc-noir', name: "Rayures blanc & noir" },
  { id: 'mur-fleuri-creme-rose', name: "Fleuri crème" },
  { id: 'mur-fleuri-blanc-bleu', name: "Fleuri blanc" },
  { id: 'mur-fleuri-ivoire-corail', name: "Fleuri ivoire" },
  { id: 'mur-fleuri-sauge-blanc', name: "Fleuri sauge" },
  { id: 'mur-fleuri-creme-lavande', name: "Fleuri crème" },
  { id: 'mur-fleuri-blanc-framboise', name: "Fleuri blanc" },
  { id: 'mur-fleuri-beige-terracotta', name: "Fleuri beige" },
  { id: 'mur-fleuri-ciel-blanc', name: "Fleuri ciel" },
  { id: 'mur-fleuri-poudre-framboise', name: "Fleuri poudré" },
  { id: 'mur-fleuri-creme-vert', name: "Fleuri crème" },
  { id: 'mur-pois-creme-terracotta', name: "Pois crème" },
  { id: 'mur-pois-blanc-bleu', name: "Pois blanc" },
  { id: 'mur-pois-sauge-creme', name: "Pois sauge" },
  { id: 'mur-pois-blanc-rose', name: "Pois blanc" },
  { id: 'mur-pois-ivoire-moutarde', name: "Pois ivoire" },
  { id: 'mur-pois-blanc-ardoise', name: "Pois blanc" },
  { id: 'mur-pois-poudre-framboise', name: "Pois poudré" },
  { id: 'mur-pois-ciel-blanc', name: "Pois ciel" },
  { id: 'mur-brique-brique', name: "Brique brique" },
  { id: 'mur-brique-rouge', name: "Brique rouge" },
  { id: 'mur-brique-blanc', name: "Brique blanc" },
  { id: 'mur-brique-gris', name: "Brique gris" },
  { id: 'mur-brique-sable', name: "Brique sable" },
  { id: 'mur-brique-ardoise', name: "Brique ardoise" },
  { id: 'mur-brique-terracotta', name: "Brique terracotta" },
  { id: 'mur-brique-creme', name: "Brique crème" },
  { id: 'mur-lambris-chene', name: "Lambris chêne" },
  { id: 'mur-lambris-noyer', name: "Lambris noyer" },
  { id: 'mur-lambris-acajou', name: "Lambris acajou" },
  { id: 'mur-lambris-hetre', name: "Lambris hêtre" },
  { id: 'mur-lambris-teck', name: "Lambris teck" },
  { id: 'mur-lambris-ebene', name: "Lambris ébène" },
  { id: 'mur-lambris-gris', name: "Lambris gris" },
  { id: 'mur-lambris-blanchi', name: "Lambris blanchi" },
  { id: 'mur-carrelage-blanc', name: "Carrelage blanc" },
  { id: 'mur-carrelage-creme', name: "Carrelage crème" },
  { id: 'mur-carrelage-menthe', name: "Carrelage menthe" },
  { id: 'mur-carrelage-ciel', name: "Carrelage ciel" },
  { id: 'mur-carrelage-rose', name: "Carrelage rose" },
  { id: 'mur-carrelage-sauge', name: "Carrelage sauge" },
  { id: 'mur-carrelage-bleu', name: "Carrelage bleu" },
  { id: 'mur-carrelage-gris', name: "Carrelage gris" },
  { id: 'mur-carrelage-moutarde', name: "Carrelage moutarde" },
  { id: 'mur-carrelage-lavande', name: "Carrelage lavande" },
  { id: 'mur-vichy-blanc-rose', name: "Vichy rose" },
  { id: 'mur-vichy-blanc-bleu', name: "Vichy bleu" },
  { id: 'mur-vichy-blanc-sauge', name: "Vichy sauge" },
  { id: 'mur-vichy-blanc-moutarde', name: "Vichy moutarde" },
  { id: 'mur-vichy-blanc-terracotta', name: "Vichy terracotta" },
  { id: 'mur-vichy-blanc-lavande', name: "Vichy lavande" },
  { id: 'mur-losange-creme-terracotta', name: "Losanges terracotta" },
  { id: 'mur-losange-blanc-ardoise', name: "Losanges ardoise" },
  { id: 'mur-losange-sauge-creme', name: "Losanges crème" },
  { id: 'mur-losange-ivoire-bordeaux', name: "Losanges bordeaux" },
  { id: 'mur-crepi-creme', name: "Crépi crème" },
  { id: 'mur-crepi-blanc', name: "Crépi blanc" },
  { id: 'mur-crepi-sable', name: "Crépi sable" },
  { id: 'mur-crepi-sauge', name: "Crépi sauge" },
  { id: 'mur-crepi-gris', name: "Crépi gris" },
  { id: 'mur-crepi-terracotta', name: "Crépi terracotta" },
];
export const MAT_PRICES: Record<string, number> = {
  'sol-bois-clair': 40,
  'sol-bois-fonce': 40,
  'sol-chevron': 60,
  'sol-carrelage-damier': 40,
  'sol-carrelage-blanc': 40,
  'sol-moquette': 50,
  'sol-beton': 40,
  'sol-marbre': 90,
  'sol-herbe': 40,
  'sol-sable': 40,
  'sol-terre': 40,
  'sol-pierre': 60,
  'sol-eau': 80,
  'sol-neige': 70,
  'sol-parquet-chene': 40,
  'sol-parquet-noyer': 40,
  'sol-parquet-acajou': 40,
  'sol-parquet-hetre': 40,
  'sol-parquet-teck': 40,
  'sol-parquet-ebene': 40,
  'sol-parquet-gris': 40,
  'sol-parquet-blanchi': 40,
  'sol-parquet-miel': 40,
  'sol-parquet-rouge': 40,
  'sol-parquet-cendre': 40,
  'sol-parquet-caramel': 40,
  'sol-chevron-chene': 60,
  'sol-chevron-noyer': 60,
  'sol-chevron-acajou': 60,
  'sol-chevron-hetre': 60,
  'sol-chevron-teck': 60,
  'sol-chevron-ebene': 60,
  'sol-chevron-gris': 60,
  'sol-chevron-blanchi': 60,
  'sol-damier-blanc-noir': 40,
  'sol-damier-blanc-gris': 40,
  'sol-damier-creme-terracotta': 40,
  'sol-damier-blanc-bleu': 40,
  'sol-damier-blanc-vert': 40,
  'sol-damier-blanc-rose': 40,
  'sol-damier-ivoire-ardoise': 40,
  'sol-damier-creme-caramel': 40,
  'sol-damier-blanc-menthe': 40,
  'sol-damier-blanc-jaune': 40,
  'sol-damier-blanc-corail': 40,
  'sol-damier-gris-anthracite': 40,
  'sol-carrelage-creme': 40,
  'sol-carrelage-gris': 40,
  'sol-carrelage-ardoise': 40,
  'sol-carrelage-sauge': 40,
  'sol-carrelage-menthe': 40,
  'sol-carrelage-bleu': 40,
  'sol-carrelage-ciel': 40,
  'sol-carrelage-rose': 40,
  'sol-carrelage-terracotta': 40,
  'sol-carrelage-moutarde': 40,
  'sol-carrelage-lavande': 40,
  'sol-marbre-blanc': 90,
  'sol-marbre-gris': 90,
  'sol-marbre-noir': 90,
  'sol-marbre-rose': 90,
  'sol-marbre-vert': 90,
  'sol-marbre-bleu': 90,
  'sol-beton-gris': 40,
  'sol-beton-grisclair': 40,
  'sol-beton-galet': 40,
  'sol-beton-sable': 40,
  'sol-beton-anthracite': 40,
  'sol-paves-galet': 60,
  'sol-paves-gris': 60,
  'sol-paves-sable': 60,
  'sol-paves-ardoise': 60,
  'sol-paves-brun': 60,
  'sol-terrazzo-creme': 70,
  'sol-terrazzo-blanc': 70,
  'sol-terrazzo-rose': 70,
  'sol-terrazzo-menthe': 70,
  'sol-terrazzo-gris': 70,
  'sol-terrazzo-sable': 70,
  'sol-moquette-vieuxrose': 50,
  'sol-moquette-gris': 50,
  'sol-moquette-sauge': 50,
  'sol-moquette-bleu': 50,
  'sol-moquette-moutarde': 50,
  'sol-moquette-lavande': 50,
  'sol-moquette-menthe': 50,
  'sol-moquette-terracotta': 50,
  'sol-gravier': 40,
  'sol-galets': 60,
  'sol-mousse': 40,
  'sol-feuilles': 40,
  'sol-glace': 70,
  'sol-lave': 80,
  'sol-boue': 40,
  'sol-ardoise': 60,
  'sol-brique-sol': 50,
  'sol-neige-glace': 70,
  'sol-mosaique-mer': 70,
  'sol-mosaique-terre': 70,
  'sol-mosaique-jardin': 70,
  'sol-mosaique-rose': 70,
  'sol-metal': 60,
  'sol-dalle-gris': 40,
  'sol-dalle-ardoise': 40,
  'sol-dalle-creme': 40,
  'sol-rayures-creme-sauge': 40,
  'sol-rayures-blanc-bleu': 40,
  'sol-rayures-creme-terracotta': 40,
  'sol-rayures-blanc-gris': 40,
  'sol-pois-creme-terracotta': 40,
  'sol-pois-blanc-ardoise': 40,
  'sol-pois-sauge-creme': 40,
  'mur-pastel': 40,
  'mur-papier-fleuri': 50,
  'mur-brique': 50,
  'mur-bois': 60,
  'mur-carrelage': 50,
  'mur-rayures': 40,
  'mur-crepi': 40,
  'mur-uni-blanc': 30,
  'mur-uni-creme': 30,
  'mur-uni-ivoire': 30,
  'mur-uni-beige': 30,
  'mur-uni-gris': 30,
  'mur-uni-grisclair': 30,
  'mur-uni-ardoise': 30,
  'mur-uni-sauge': 30,
  'mur-uni-menthe': 30,
  'mur-uni-vert': 30,
  'mur-uni-olive': 30,
  'mur-uni-bleu': 30,
  'mur-uni-ciel': 30,
  'mur-uni-canard': 30,
  'mur-uni-turquoise': 30,
  'mur-uni-rose': 30,
  'mur-uni-poudre': 30,
  'mur-uni-corail': 30,
  'mur-uni-moutarde': 30,
  'mur-uni-jaune': 30,
  'mur-uni-lilas': 30,
  'mur-uni-lavande': 30,
  'mur-uni-violet': 30,
  'mur-uni-taupe': 30,
  'mur-rayures-blanc-bleu': 40,
  'mur-rayures-blanc-sauge': 40,
  'mur-rayures-creme-terracotta': 40,
  'mur-rayures-blanc-rose': 40,
  'mur-rayures-blanc-gris': 40,
  'mur-rayures-creme-menthe': 40,
  'mur-rayures-blanc-moutarde': 40,
  'mur-rayures-blanc-lavande': 40,
  'mur-rayures-ivoire-canard': 40,
  'mur-rayures-blanc-corail': 40,
  'mur-rayures-creme-vert': 40,
  'mur-rayures-blanc-ardoise': 40,
  'mur-rayures-poudre-blanc': 40,
  'mur-rayures-ciel-blanc': 40,
  'mur-rayures-creme-bordeaux': 40,
  'mur-rayures-blanc-noir': 40,
  'mur-fleuri-creme-rose': 50,
  'mur-fleuri-blanc-bleu': 50,
  'mur-fleuri-ivoire-corail': 50,
  'mur-fleuri-sauge-blanc': 50,
  'mur-fleuri-creme-lavande': 50,
  'mur-fleuri-blanc-framboise': 50,
  'mur-fleuri-beige-terracotta': 50,
  'mur-fleuri-ciel-blanc': 50,
  'mur-fleuri-poudre-framboise': 50,
  'mur-fleuri-creme-vert': 50,
  'mur-pois-creme-terracotta': 40,
  'mur-pois-blanc-bleu': 40,
  'mur-pois-sauge-creme': 40,
  'mur-pois-blanc-rose': 40,
  'mur-pois-ivoire-moutarde': 40,
  'mur-pois-blanc-ardoise': 40,
  'mur-pois-poudre-framboise': 40,
  'mur-pois-ciel-blanc': 40,
  'mur-brique-brique': 50,
  'mur-brique-rouge': 50,
  'mur-brique-blanc': 50,
  'mur-brique-gris': 50,
  'mur-brique-sable': 50,
  'mur-brique-ardoise': 50,
  'mur-brique-terracotta': 50,
  'mur-brique-creme': 50,
  'mur-lambris-chene': 60,
  'mur-lambris-noyer': 60,
  'mur-lambris-acajou': 60,
  'mur-lambris-hetre': 60,
  'mur-lambris-teck': 60,
  'mur-lambris-ebene': 60,
  'mur-lambris-gris': 60,
  'mur-lambris-blanchi': 60,
  'mur-carrelage-blanc': 50,
  'mur-carrelage-creme': 50,
  'mur-carrelage-menthe': 50,
  'mur-carrelage-ciel': 50,
  'mur-carrelage-rose': 50,
  'mur-carrelage-sauge': 50,
  'mur-carrelage-bleu': 50,
  'mur-carrelage-gris': 50,
  'mur-carrelage-moutarde': 50,
  'mur-carrelage-lavande': 50,
  'mur-vichy-blanc-rose': 40,
  'mur-vichy-blanc-bleu': 40,
  'mur-vichy-blanc-sauge': 40,
  'mur-vichy-blanc-moutarde': 40,
  'mur-vichy-blanc-terracotta': 40,
  'mur-vichy-blanc-lavande': 40,
  'mur-losange-creme-terracotta': 40,
  'mur-losange-blanc-ardoise': 40,
  'mur-losange-sauge-creme': 40,
  'mur-losange-ivoire-bordeaux': 40,
  'mur-crepi-creme': 40,
  'mur-crepi-blanc': 40,
  'mur-crepi-sable': 40,
  'mur-crepi-sauge': 40,
  'mur-crepi-gris': 40,
  'mur-crepi-terracotta': 40,
};
export const FREE_MATS = new Set<string>(['sol-bois-clair', 'sol-bois-fonce', 'sol-carrelage-blanc', 'sol-herbe', 'sol-sable', 'mur-pastel', 'mur-papier-fleuri', 'mur-bois', 'mur-carrelage', 'mur-rayures']);
