-- Précision des compétences : chaque compétence reçoit une description claire
-- (ce que c'est + niveau scolaire + critère de maîtrise), transmise à l'IA-prof
-- pour qu'elle enseigne EXACTEMENT le bon sujet au bon niveau (fin des dérives).
update public.skills set description = $$Regrouper des objets selon un critère (couleur, taille, forme) et les ranger dans un ordre (croissant/décroissant). Niveau maternelle. Maîtrisé quand l'élève trie et ordonne seul une petite collection selon un critère donné.$$ where title = 'Classer et ordonner';
update public.skills set description = $$Dire si une collection a plus, moins ou autant d'éléments qu'une autre, sans forcément compter. Niveau maternelle. Maîtrisé quand l'élève compare correctement deux collections proches.$$ where title = 'Comparer des quantités';
update public.skills set description = $$Écouter et comprendre des consignes, une histoire ou une question dites à l'oral. Niveau maternelle. Maîtrisé quand l'élève répond correctement à des questions sur un court récit entendu.$$ where title = 'Comprendre l''oral (langue maternelle)';
update public.skills set description = $$Contrôler et enchaîner ses mouvements de façon fluide et précise (motricité globale et fine : sauter, lancer, tenir un crayon). Niveau maternelle. Maîtrisé quand l'élève réalise un enchaînement de gestes coordonnés de façon contrôlée.$$ where title = 'Coordonner son corps';
update public.skills set description = $$Associer les lettres et groupes de lettres aux sons (correspondance graphème-phonème), puis lire à voix haute des syllabes, des mots et de courtes phrases. Il s'agit de la lecture de TEXTE (pas de musique). Niveau CP (début de primaire). Maîtrisé quand l'élève lit seul un mot ou une phrase simple inconnus, sans les deviner.$$ where title = 'Déchiffrer et lire';
update public.skills set description = $$Compter une collection en associant un nombre à chaque objet et en donnant le total. Niveau maternelle/CP. Maîtrisé quand l'élève dénombre sans erreur une collection jusqu'à environ 20.$$ where title = 'Dénombrer';
update public.skills set description = $$Tenir un crayon et tracer lettres et chiffres de façon lisible (geste graphique). Niveau maternelle/CP. Maîtrisé quand l'élève écrit lisiblement les lettres et son prénom.$$ where title = 'Écrire et tracer';
update public.skills set description = $$Communiquer avec les autres : écouter, attendre son tour, exprimer un besoin, coopérer. Niveau maternelle. Maîtrisé quand l'élève participe à un échange ou un jeu de groupe en respectant les règles.$$ where title = 'Interagir avec autrui';
update public.skills set description = $$Regarder attentivement et décrire ce qu'on voit avec des mots précis (formes, couleurs, différences). Niveau maternelle. Maîtrisé quand l'élève décrit une image ou un objet avec plusieurs détails pertinents.$$ where title = 'Observer et décrire';
update public.skills set description = $$Identifier et nommer ses émotions et celles des autres (joie, colère, peur, tristesse). Niveau maternelle. Maîtrisé quand l'élève nomme correctement l'émotion sur un visage ou dans une situation.$$ where title = 'Reconnaître les émotions';
update public.skills set description = $$Parler pour se faire comprendre : formuler une phrase, raconter, poser une question. Niveau maternelle. Maîtrisé quand l'élève raconte un petit événement de façon compréhensible.$$ where title = 'S''exprimer à l''oral (langue maternelle)';
update public.skills set description = $$Utiliser les repères d'espace (devant/derrière, gauche/droite) et de temps (avant/après, hier/demain). Niveau maternelle. Maîtrisé quand l'élève se situe et situe des événements avec ces repères.$$ where title = 'Se repérer dans l''espace et le temps';
update public.skills set description = $$Calculer une somme (ajouter deux nombres), d'abord par comptage puis mentalement. Niveau CP. Maîtrisé quand l'élève additionne sans erreur des nombres jusqu'à environ 20.$$ where title = 'Additionner';
update public.skills set description = $$Écrire seul une phrase simple qui a du sens, avec majuscule et point. Niveau CP/CE1. Maîtrisé quand l'élève écrit une phrase correcte et compréhensible.$$ where title = 'Écrire une phrase';
update public.skills set description = $$Lire un court texte et en comprendre le sens (répondre à des questions dessus). Niveau CP/CE1. Maîtrisé quand l'élève répond correctement à des questions sur un texte court lu seul.$$ where title = 'Lire et comprendre un texte simple';
update public.skills set description = $$Calculer une différence (retirer, comparer, compléter). Niveau CP/CE1. Maîtrisé quand l'élève soustrait sans erreur des nombres jusqu'à environ 20.$$ where title = 'Soustraire';
update public.skills set description = $$Comprendre la multiplication comme une addition répétée et connaître les premières tables. Niveau CE1/CE2. Maîtrisé quand l'élève résout des multiplications simples et connaît les tables usuelles.$$ where title = 'Multiplier';
update public.skills set description = $$Écrire plusieurs phrases qui s'enchaînent pour raconter ou expliquer. Niveau CE1/CE2. Maîtrisé quand l'élève produit un court texte cohérent de quelques phrases.$$ where title = 'Rédiger un court texte';
update public.skills set description = $$Lire un énoncé, choisir la bonne opération et calculer la réponse. Niveau CE1/CE2. Maîtrisé quand l'élève résout seul un problème simple à une étape.$$ where title = 'Résoudre un problème arithmétique';
update public.skills set description = $$Dégager l'essentiel d'un texte et le redire en quelques mots. Niveau CE2. Maîtrisé quand l'élève restitue l'idée principale et les points clés d'un texte court.$$ where title = 'Résumer un texte';
update public.skills set description = $$Défendre un point de vue à l'écrit avec des arguments et des exemples. Niveau CM. Maîtrisé quand l'élève écrit un court texte argumenté et clair.$$ where title = 'Argumenter à l''écrit';
update public.skills set description = $$Comprendre une fraction comme une part d'un tout (1/2, 1/4) et comparer des fractions simples. Niveau CM. Maîtrisé quand l'élève manipule et compare des fractions simples.$$ where title = 'Comprendre les fractions simples';
update public.skills set description = $$Comprendre la division comme un partage ou un groupement et poser des divisions simples. Niveau CM. Maîtrisé quand l'élève résout des divisions simples.$$ where title = 'Diviser';
